# Generated by Django 3.2.19 on 2023-06-20 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('steg', '0002_users_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2023, 6, 20, 6, 52, 37, 919153, tzinfo=utc))),
                ('author', models.CharField(default='npoudelp', max_length=25)),
            ],
        ),
    ]
