# Generated by Django 3.2.19 on 2023-06-20 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('steg', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.datetime(2023, 6, 20, 12, 45, 11, 370824, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 12, 45, 11, 370550, tzinfo=utc)),
        ),
    ]
