# Generated by Django 3.2.19 on 2023-06-21 06:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('steg', '0005_auto_20230621_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 6, 46, 39, 879534, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 6, 46, 39, 879924, tzinfo=utc)),
        ),
    ]
