# Generated by Django 4.2.2 on 2023-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blood_doner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=3)),
                ('bGroup', models.CharField(max_length=10)),
                ('phone', models.IntegerField(max_length=13)),
            ],
        ),
    ]
